import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const IRANSansX = localFont({
  src: "../fonts/IRANSansXFaNum-Regular.woff2",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Saman E pay Task",
  description: "Generated by Haj Aqa Amirmohammad",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${IRANSansX.className} `}>

        <div className="bg-slate-100 min-h-screen">{children}</div>
      </body>
    </html>
  );
}
